/**
 * Message protocol between SharedMicroVecDB (client) and the SharedWorker host.
 *
 * Every request carries a `reqId` (monotonic integer generated by the client).
 * The worker echoes it back in the response so the client can resolve the
 * correct Promise.
 */

// ── Requests (client → worker) ────────────────────────────────────────────────

/** Each variant without `reqId` — used by the client's `send()` helper. */
export type WorkerRequestBody =
  | { type: 'init';          capacity: number; persistenceKey: string | null; hnswM: number; hnswEfConstruction: number }
  | { type: 'insert';        id: number; vector: Float32Array }
  | { type: 'insert_batch';  ids: Uint32Array; flat: Float32Array }
  | { type: 'search_scan';   query: Float32Array; k: number }
  | { type: 'search_hnsw';   query: Float32Array; k: number; ef: number }
  | { type: 'build_index';   m: number; efConstruction: number }
  | { type: 'delete';        id: number }
  | { type: 'compact' }
  | { type: 'save' }
  | { type: 'clear_save' }
  | { type: 'serialize' }
  | { type: 'stats' }
  | { type: 'dispose' };

/** Full on-wire request — `reqId` added by `send()`. */
export type WorkerRequest = WorkerRequestBody & { reqId: number };

// ── Responses (worker → client) ───────────────────────────────────────────────

export type WorkerResponse =
  | { type: 'ok';    reqId: number; payload?: unknown }
  | { type: 'error'; reqId: number; message: string };

export interface DbStatsPayload {
  count: number;
  hasIndex: boolean;
}
